//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Settings:.
        /// </summary>
        public static string ClientSettings {
            get {
                return ResourceManager.GetString("ClientSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        public static string HostNameTxt {
            get {
                return ResourceManager.GetString("HostNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client..
        /// </summary>
        public static string InvalidClient {
            get {
                return ResourceManager.GetString("InvalidClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection..
        /// </summary>
        public static string InvalidConnection {
            get {
                return ResourceManager.GetString("InvalidConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host name..
        /// </summary>
        public static string InvalidHostName {
            get {
                return ResourceManager.GetString("InvalidHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port name..
        /// </summary>
        public static string InvalidPortName {
            get {
                return ResourceManager.GetString("InvalidPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string PortTxt {
            get {
                return ResourceManager.GetString("PortTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string ProtocolTxt {
            get {
                return ResourceManager.GetString("ProtocolTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Settings:.
        /// </summary>
        public static string ServerSettings {
            get {
                return ResourceManager.GetString("ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ServerTxt {
            get {
                return ResourceManager.GetString("ServerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Settings.
        /// </summary>
        public static string SettingsTxt {
            get {
                return ResourceManager.GetString("SettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use IPv6.
        /// </summary>
        public static string UseIPv6Txt {
            get {
                return ResourceManager.GetString("UseIPv6Txt", resourceCulture);
            }
        }
    }
}
