//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peruuttaa.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asiakkaan asetukset.
        /// </summary>
        internal static string ClientSettings {
            get {
                return ResourceManager.GetString("ClientSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joko Count tai Eop on asetettava..
        /// </summary>
        internal static string EitherCountOrEopMustBeSet {
            get {
                return ResourceManager.GetString("EitherCountOrEopMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isäntä :.
        /// </summary>
        internal static string HostNameTxt {
            get {
                return ResourceManager.GetString("HostNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virheellinen asiakas..
        /// </summary>
        internal static string InvalidClient {
            get {
                return ResourceManager.GetString("InvalidClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virheellinen liitäntä ..
        /// </summary>
        internal static string InvalidConnection {
            get {
                return ResourceManager.GetString("InvalidConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virheellinen palvelimen nimi ..
        /// </summary>
        internal static string InvalidHostName {
            get {
                return ResourceManager.GetString("InvalidHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virheellinen portin nimi ..
        /// </summary>
        internal static string InvalidPortName {
            get {
                return ResourceManager.GetString("InvalidPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port :.
        /// </summary>
        internal static string PortTxt {
            get {
                return ResourceManager.GetString("PortTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ominaisuudet.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protokolla.
        /// </summary>
        internal static string ProtocolTxt {
            get {
                return ResourceManager.GetString("ProtocolTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palvelimen asetukset :.
        /// </summary>
        internal static string ServerSettings {
            get {
                return ResourceManager.GetString("ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palvelin.
        /// </summary>
        internal static string ServerTxt {
            get {
                return ResourceManager.GetString("ServerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkkoasetukset.
        /// </summary>
        internal static string SettingsTxt {
            get {
                return ResourceManager.GetString("SettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to käytä IPv6.
        /// </summary>
        internal static string UseIPv6Txt {
            get {
                return ResourceManager.GetString("UseIPv6Txt", resourceCulture);
            }
        }
    }
}
